# dockerfile: api.Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY requirements-api.txt .

RUN pip install --no-cache-dir -r requirements-api.txt

COPY ./main.py ./
COPY ./tasks.py ./

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]